do
    keyDescriptions['toggle_repeat_build'] = 'Toggle factory repeat build'
    keyDescriptions['show_enemy_life'] = 'Show enemy life bars'
    keyDescriptions['show_network_stats'] = 'Show network stats window'
    keyDescriptions['scu_upgrade_marker'] = 'Place SCU auto-upgrade marker'
    keyDescriptions['toggle_shield'] = 'Toggle unit shield'
    keyDescriptions['toggle_weapon'] = 'Toggle unit weapon'
    keyDescriptions['toggle_jamming'] = 'Toggle unit jamming'
    keyDescriptions['toggle_intel'] = 'Toggle unit intel'
    keyDescriptions['toggle_production'] = 'Toggle unit production'
    keyDescriptions['toggle_stealth'] = 'Toggle unit stealth'
    keyDescriptions['toggle_generic'] = 'Toggle unit generic'
    keyDescriptions['toggle_special'] = 'Toggle unit special'
    keyDescriptions['toggle_cloak'] = 'Toggle unit cloak'
    keyDescriptions['toggle_all'] = 'Toggle all unit abilities'
    keyDescriptions['teleport'] = 'Teleport'
    keyDescriptions['military_overlay'] = 'Show all weapon ranges'
    keyDescriptions['intel_overlay'] = 'Show all intel ranges'
    keyDescriptions['select_all_idle_eng_onscreen'] = 'Select idle engineers on screen'
    keyDescriptions['select_all_similar_units'] = 'Select all similarly upgraded units'
    keyDescriptions['select_next_land_factory'] = 'Select next land factory'
    keyDescriptions['select_next_air_factory'] = 'Select next air factory'
    keyDescriptions['select_next_naval_factory'] = 'Select next naval factory'
    keyDescriptions['toggle_selectedinfo'] = 'Toggle single unit selected info'
    keyDescriptions['toggle_selectedrings'] = 'Toggle single unit selected rings'
    keyDescriptions['toggle_cloakjammingstealth'] = 'Toggle all counter-intelligence abilities'
    keyDescriptions['toggle_intelshield'] = 'Toggle intel and shield'
    keyDescriptions['toggle_mdf_panel'] = 'Toggle MFD panel'
    keyDescriptions['toggle_tab_display'] = 'Toggle options tab'
    keyDescriptions['zoom_pop'] = 'One-key zoom-pop'
    keyDescriptions['select_inview_idle_mex'] = 'Select onscreen idle mass extractors.'
    keyDescriptions['select_all_mex'] = 'Select all mass extractors.'
    keyDescriptions['select_nearest_idle_lt_mex'] = 'Select nearest onscreen lowest tech idle mass extractor.'

    keyDescriptions['acu_select_cg'] = 'Select ACU (control group)'
    keyDescriptions['acu_append_cg'] = 'Append ACU to selection (control group)'
    keyDescriptions['select_nearest_idle_eng_not_acu'] = 'Select nearest idle engineer (not ACU)'
    keyDescriptions['add_nearest_idle_engineers_seq'] = 'Select/Add nearest idle engineers'
    keyDescriptions['cycle_idle_factories'] = 'Cycle through idle factories'
    keyDescriptions['cycle_unit_types_in_sel'] = 'Cycle through unit types in selection (Land, Sea, Air)'

    keyDescriptions['create_template_factory'] = 'Create build template (Factory)'

    keyDescriptions['select_gunships'] = 'Select all Gunships'
    keyDescriptions['select_anti_air_fighters'] = 'Select all Air Fighters'
    keyDescriptions['select_all_tml'] = 'Select all TML'
    keyDescriptions['select_all_stationdrones'] = 'Select all Drones'
    keyDescriptions['select_all_t2_podstations'] = 'Select all T2 Engineering Podstations'
    keyDescriptions['select_all_air_exp'] = 'Select all Air Experimentals'
    keyDescriptions['select_all_antinavy_subs'] = 'Select all anti-Navy Submarines'
    keyDescriptions['select_all_land_exp'] = 'Select all Land Experimentals'
    keyDescriptions['select_all_land_indirectfire'] = 'Select all Land Indirect-Fire units'
    keyDescriptions['select_all_land_directfire'] = 'Select all Land Direct-Fire units'
    keyDescriptions['select_all_air_factories'] = 'Select all Air Factories'
    keyDescriptions['select_all_land_factories'] = 'Select all Land Factories'
    keyDescriptions['select_all_naval_factories'] = 'Select all Naval Factories'
    keyDescriptions['select_all_t1_engineers'] = 'Select all T1 Engineers'
    keyDescriptions['select_all_battleships'] = 'Select all Battleships'

    keyDescriptions['Render_SelectionSet_Names'] = 'Toggles display of group names'
    keyDescriptions['Render_Custom_Names'] = 'Toggles display of custom names'
    keyDescriptions['Render_Unit_Bars'] = 'Toggle display of names and bars of any kind'
    keyDescriptions['Render_Icons'] = 'Toggle display of Strategic Icons'
    keyDescriptions['Always_Render_Strategic_Icons'] = 'Toggle strategic icon cutoff'
    keyDescriptions['Kill_Selected_Units'] = 'Immediately kill selected units'
    keyDescriptions['Kill_All'] = 'Immediately kill all of your units'
    keyDescriptions['Show_Bandwidth_Usage'] = 'Show bandwith usage window'
    keyDescriptions['Execute_Paste_Buffer'] = '[Debug] Execute Paste Buffer'

end
